version: '3.8'


services:
  web:
    container_name: web
    build: ./backend
    command: "sh -c 'uvicorn app.main:app --reload'"
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file: ".env"
    depends_on:
      - database
    
  database:
    image: postgres:latest
    container_name: database
    env_file: ".env"
    user: root
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_SERVER}
      - POSTGRES_HOST_AUTH_METHOD= "trust"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: ".env"
    ports:
      - 5050:80
    depends_on:
      - database
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

    

